# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build crudapp`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t crudapp`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system crudapp && \
          adduser --system -G crudapp crudapp

COPY dist/crudapp crudapp
RUN chown -R crudapp:crudapp .

CMD [ "node", "crudapp" ]
